# Using EcoFOCIpy to process raw field data

## Cruise ID - DY2307

## BTL Data + Nutrient Data

This is a streamlined version of generation routines to merge bottle data and Mordy Nut. Lab Nutrient Data for long term archive

In [1]:
import yaml
import glob
import pandas as pd

import EcoFOCIpy.io.sbe_ctd_parser as sbe_ctd_parser #<- instrument specific
import EcoFOCIpy.io.ncCFsave as ncCFsave
import EcoFOCIpy.metaconfig.load_config as load_config

In [4]:
sample_data_dir = '/Users/bell/ecoraid/2023/CTDcasts/dy2307/' #root path to cruise directory
ecofocipy_dir = '/Users/bell/Programs/EcoFOCIpy/'

In [5]:
###############################################################
# edit to point to {cruise sepcific} raw datafiles 
datafile = sample_data_dir+'rawconverted/' #<- point to cruise and process all files within
nutdatafile = sample_data_dir+'working/DiscreteNutrients/DY2307 Nutrient Data.txt' #<- point to cruise and process all files within
cruise_name = 'dy2307' #no hyphens
cruise_meta_file = sample_data_dir+'logs/dy2307.yaml'
inst_meta_file = sample_data_dir+'logs/FOCI_standard_CTDpNutsWOCE.yaml' #<- copy to each deployment for simplicity?
group_meta_file = ecofocipy_dir+'staticdata/institutional_meta_example.yaml'
###############################################################

#init and load data
cruise = sbe_ctd_parser.sbe_btl()
filename_list = sorted(glob.glob(datafile + '*.btl'))

cruise_data = cruise.manual_parse(filename_list)

Processing /Users/bell/ecoraid/2023/CTDcasts/dy2307/rawconverted/ctd001.btl
Processing /Users/bell/ecoraid/2023/CTDcasts/dy2307/rawconverted/ctd002.btl
Processing /Users/bell/ecoraid/2023/CTDcasts/dy2307/rawconverted/ctd003.btl
Processing /Users/bell/ecoraid/2023/CTDcasts/dy2307/rawconverted/ctd004.btl
Processing /Users/bell/ecoraid/2023/CTDcasts/dy2307/rawconverted/ctd005.btl

/Users/bell/src/ecofocipy/src/EcoFOCIpy/io/sbe_ctd_parser.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ctd_df = pd.concat([ctd_df,row])
/Users/bell/src/ecofocipy/src/EcoFOCIpy/io/sbe_ctd_parser.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ctd_df = pd.concat([ctd_df,row])
/Users/bell/src/ecofocipy/src/EcoFOCIpy/io/sbe_ctd_parser.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ctd_df = pd.concat([ctd_df,row])
/Users/bell/src/ecofocipy/src/EcoFOCIpy/io/sbe_ctd_parser.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ctd_df = pd.concat([ctd_df,row])
/Users/bell/src/ecofocipy/src/EcoFOCIpy/io/sbe_ctd_parser.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  ctd_df = pd.concat([ctd_df,row])

In [6]:
# for SKQ only - drop lat/lon from datafile in lew of metadata source
# cruise_data = {}
# for cast,cdata in cruise_data_temp.items():
#     cdata.drop(labels=['latitude','longitude'],axis=1,inplace=True)
#     cruise_data.update({cast:cdata})

## Load csv Nutrient File

In [7]:
nut_data = pd.read_csv(nutdatafile,delimiter='\t')
nut_data

,Cast,Niskin,PO4 (uM),PO4_Flag,Sil (uM),Sil_Flag,NO3 (uM),NO3_Flag,NO2 (uM),NO2_Flag,NH4 (uM),NH4_Flag
0,1,8,1.100,2,18.9,2,10.5,2,0.18,2,0.64,2
1,1,7,1.266,2,23.3,2,12.7,6,0.19,6,0.71,6
2,1,6,1.201,2,21.2,2,11.7,2,0.19,2,0.79,2
3,1,5,1.448,6,29.2,6,15.7,2,0.18,2,0.26,2
4,1,4,1.451,2,28.9,2,15.8,2,0.18,2,0.27,2
5,1,3,1.559,2,30.8,2,17.3,2,0.18,2,0.55,2
6,1,2,1.659,2,35.4,2,18.4,2,0.17,2,0.52,2
7,1,1,1.659,2,32.2,2,18.3,2,0.16,2,0.78,2
8,2,1,1.659,2,30.7,2,17.9,2,0.15,2,0.99,2
9,2,2,1.645,2,31.3,2,18.0,6,0.14,6,0.88,6
10,2,3,1.594,2,32.8,2,17.2,2,0.15,2,0.66,2
11,2,4,1.642,6,31.6,6,18.1,2,0.16,2,0.53,2
12,2,5,1.676,2,31.9,2,17.9,2,0.16,2,0.55,2
13,2,6,1.613,2,30.7,2,17.1,2,0.16,2,0.63,2
14,2,7,0.950,2,11.2,2,7.1,2,0.12,2,0.41,2
15,2,8,0.636,2,3.4,2,1.8,2,0.10,2,0.12,2
16,2,9,0.600,2,4.8,2,1.5,2,0.11,2,0.07,2
17,3,7,1.314,2,24.1,2,12.8,6,0.18,6,0.75,6
18,3,6,1.353,2,24.4,2,13.1,2,0.18,2,0.91,2
19,3,5,1.393,6,25.0,6,14.0,2,0.18,2,0.94,2
20,3,4,1.402,2,25.7,2,14.1,2,0.17,2,1.03,2
21,3,3,1.489,2,27.5,2,15.4,2,0.17,2,1.05,2
22,3,2,1.613,2,31.1,2,17.2,2,0.17,2,0.96,2
23,3,1,1.631,2,32.1,2,17.7,2,0.16,2,1.07,2
24,4,1,1.572,2,29.1,2,16.6,2,0.18,2,0.92,2
25,4,2,1.447,2,26.5,2,15.2,6,0.20,6,0.75,6
26,4,3,1.404,2,23.2,2,12.5,2,0.16,2,0.64,2
27,4,4,1.428,6,26.9,6,14.7,2,0.19,2,0.78,2
28,4,5,1.419,2,26.2,2,14.5,2,0.20,2,0.85,2
29,4,6,1.400,2,25.4,2,14.4,2,0.20,2,0.82,2
30,4,7,1.418,2,26.2,2,14.5,2,0.19,2,0.83,2
31,5,11,1.025,2,18.5,2,8.0,2,0.17,2,0.26,2
32,5,10,1.065,2,18.4,2,8.6,2,0.17,2,0.34,2
33,5,9,1.155,2,19.0,2,10.0,6,0.15,6,0.44,6
34,5,8,1.219,2,19.9,2,10.9,2,0.16,2,0.65,2
35,5,7,1.241,6,20.2,6,11.2,2,0.17,2,0.69,2
36,5,6,1.244,2,20.3,2,11.2,2,0.16,2,0.56,2
37,5,5,1.523,2,26.0,2,15.2,2,0.17,2,1.27,2
38,5,4,1.799,2,33.4,2,20.4,2,0.19,2,0.81,2
39,5,3,2.350,2,50.0,2,31.0,2,0.05,2,0.02,2
40,5,2,2.589,2,58.5,2,34.8,2,0.00,2,0.03,2
41,5,1,2.760,2,66.0,2,37.4,2,0.01,2,0.33,2

## Merge Bottle and Nutrient Data but drop non nutrient vars?

In [8]:
keep_param = ['bottle','prdm']
# keep_param = ['bottle','prsm']

for cast,cdata in cruise_data.items():
    try:
        matchcast = int((cast.split('.')[0]).lower().split('ctd')[-1])
        cruise_data[cast] = pd.merge(nut_data[nut_data['Cast']==matchcast],cdata.reset_index()[keep_param],right_on='bottle',left_on='Niskin').set_index('bottle').drop(columns=['Cast'])
    except:
        continue

## Add Deployment meta information

In [9]:
#just a dictionary of dictionaries - simple
with open(cruise_meta_file) as file:
    cruise_config = yaml.full_load(file)

## Add Instrument meta information

Time, depth, lat, lon should be added regardless (always our coordinates) but for a mooring site its going to be a (1,1,1,t) dataset
The variables of interest should be read from the data file and matched to a key for naming.  That key is in the inst_config file seen below and should represent common conversion names in the raw data

In [11]:
with open(inst_meta_file) as file:
    inst_config = yaml.full_load(file)

## Add institutional meta-information

In [12]:
with open(group_meta_file) as file:
    group_config = yaml.full_load(file)

## Save CF Netcdf files

Currently stick to netcdf3 classic... but migrating to netcdf4 (default) may be no problems for most modern purposes.  Its easy enough to pass the `format` kwargs through to the netcdf api of xarray.

In [13]:
#loop over all casts and perform tasks shown above

for cast in cruise_data.keys():
    try:
        cruise_data[cast] = cruise_data[cast].rename(columns={
                            'Sil (uM)':'SI',
                            'PO4 (uM)':'PO4',
                            'NO2 (uM)':'NO2', 
                            'NO3 (uM)':'NO3',
                            'NH4 (uM)':'NH4',
                            'Sil_Flag':'SI_WOCE_FLAG',
                            'PO4_Flag':'PO4_WOCE_FLAG',
                            'NO2_Flag':'NO2_WOCE_FLAG', 
                            'NO3_Flag':'NO3_WOCE_FLAG',
                            'NH4_Flag':'NH4_WOCE_FLAG',
                            'Niskin':'BTLID',
                            'prdm':'pressure',
                            'empty':'empty', #this will be ignored
                            'flag':'flag'})

        cruise_data_nc = ncCFsave.EcoFOCI_CFnc(df=cruise_data[cast], 
                                    instrument_yaml=inst_config, 
                                    operation_yaml=cruise_config,
                                    operation_type='ctd')

        cruise_data_nc.expand_dimensions(dim_names=['latitude','longitude','time'],geophys_sort=False)

        cruise_data_nc.variable_meta_data(variable_keys=list(cruise_data[cast].columns.values),drop_missing=False)
        #adding dimension meta needs to come after updating the dimension values... BUG?
        cruise_data_nc.dimension_meta_data(variable_keys=['time','latitude','longitude'])
        cruise_data_nc.temporal_geospatioal_meta_data_ctd(positiveE=False,conscastno=cast.split('.')[0])

        #add global attributes
        cruise_data_nc.deployment_meta_add(conscastno=cast.split('.')[0].upper())

        #add instituitonal global attributes
        cruise_data_nc.institution_meta_add(group_config)

        #add creation date/time - provenance data
        cruise_data_nc.provinance_meta_add()

        #provide intial qc status field
        cruise_data_nc.qc_status(qc_status='excellent') #<- options are unknown, excellent, probably good, mixed, unqcd

        cast = cast.lower().split('d')[-1].split('.')[0]
        cruise_data_nc.xarray2netcdf_save(xdf = cruise_data_nc.get_xdf(),
                                   filename=cruise_name+'c'+cast.zfill(3)+'_nut.nc',format="NETCDF3_CLASSIC")
    except:
        print(f'Skipping {cast}')

/Users/bell/src/ecofocipy/src/EcoFOCIpy/io/ncCFsave.py:320: UserWarning: Times can't be serialized faithfully to int64 with requested units 'days since 1900-01-01'. Resolution of 'minutes' needed. Serializing times to floating point instead. Set encoding['dtype'] to integer dtype to serialize to int64. Set encoding['dtype'] to floating point dtype to silence this warning.
  xdf.to_netcdf(filename,format=kwargs['format'],encoding={'time':{'units':'days since 1900-01-01'}})
/Users/bell/src/ecofocipy/src/EcoFOCIpy/io/ncCFsave.py:320: UserWarning: Times can't be serialized faithfully to int64 with requested units 'days since 1900-01-01'. Resolution of 'minutes' needed. Serializing times to floating point instead. Set encoding['dtype'] to integer dtype to serialize to int64. Set encoding['dtype'] to floating point dtype to silence this warning.
  xdf.to_netcdf(filename,format=kwargs['format'],encoding={'time':{'units':'days since 1900-01-01'}})
/Users/bell/src/ecofocipy/src/EcoFOCIpy/io/ncCFsave.py:320: UserWarning: Times can't be serialized faithfully to int64 with requested units 'days since 1900-01-01'. Resolution of 'minutes' needed. Serializing times to floating point instead. Set encoding['dtype'] to integer dtype to serialize to int64. Set encoding['dtype'] to floating point dtype to silence this warning.
  xdf.to_netcdf(filename,format=kwargs['format'],encoding={'time':{'units':'days since 1900-01-01'}})
/Users/bell/src/ecofocipy/src/EcoFOCIpy/io/ncCFsave.py:320: UserWarning: Times can't be serialized faithfully to int64 with requested units 'days since 1900-01-01'. Resolution of 'minutes' needed. Serializing times to floating point instead. Set encoding['dtype'] to integer dtype to serialize to int64. Set encoding['dtype'] to floating point dtype to silence this warning.
  xdf.to_netcdf(filename,format=kwargs['format'],encoding={'time':{'units':'days since 1900-01-01'}})
/Users/bell/src/ecofocipy/src/EcoFOCIpy/io/ncCFsave.py:320: UserWarning: Times can't be serialized faithfully to int64 with requested units 'days since 1900-01-01'. Resolution of 'minutes' needed. Serializing times to floating point instead. Set encoding['dtype'] to integer dtype to serialize to int64. Set encoding['dtype'] to floating point dtype to silence this warning.
  xdf.to_netcdf(filename,format=kwargs['format'],encoding={'time':{'units':'days since 1900-01-01'}})

## Next Steps

QC of data (plot parameters with other instruments)
- be sure to updated the qc_status and the history